### ISSUE TITLE
`/abc/def/....html`のようなURLだとjavascriptやCSSが読み込まれない。

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-frontend#1]
タイトル通りです。
恐らく原因はjs, cssなどの指定が`js/main.js`のようになっているから。
`/js/main.js`にすれば恐らく治る。

**Comment by Takkun053** [comment]
読み込まれてますが？

**Comment by tasuren** [comment]
僕がやったとき読み込まれなかった。
(ウェブ認証終了後の`rt-bot.com/api/captcha`)

**Comment by tasuren** [comment]
それとログにも404エラーである。

**Comment by Takkun053** [comment]
ウェブ認証の担当はたすれんでは？

**Comment by tasuren** [comment]
> ウェブ認証の担当はたすれんでは？

そうじゃない、HTMLでの問題だからこれはフロントエンドに相当する。

**Comment by Takkun053** [comment]
普通にcaptcha.htmlのurlを変更すればいいのでは

**Comment by tasuren** [comment]
> 普通にcaptcha.htmlのurlを変更すればいいのでは

おとなしく直せばいいのに()

**Comment by Takkun053** [comment]
他のファイルは直す必要がないんだから。
それに、そのファイルを作るときに他のファイルをコピーしたのはたすれんでしょ？

**Comment by tasuren** [comment]
いや元ファイルを作ったのはTakkunじゃん()

なんでそんなに嫌がるの？

**Comment by tasuren** [comment]
もうらちあかん
めんどくさいんなら僕がPRだすわ

**Comment by Takkun053** [comment]
え、元ファイルなんて作ったっけ？

**Comment by tasuren** [comment]
> え、元ファイルなんて作ったっけ？
> 
> > なんでそんなに嫌がるの？
> 
> いま他のことしてて忙しいから

忙しいんなら後でやっとくっていやあええやん
もうええわ

**Comment by tasuren** [comment]
修正した。
