### ISSUE TITLE
ウェブのヘルプを軽くリニューアル

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-frontend#3]
左にカテゴリーメニューがあり右にコマンド一覧が表示され動的なページにしたい。

* [ ] デザインを作る。
* [ ] CSSの作成をする。
* [ ] JSを作る。

**Comment by tuna2134** [comment]
検索機能も欲しいね

**Comment by tasuren** [comment]
ダッシュボードのコマンド一覧をカテゴリー分けしたみたいにする予定
