### ISSUE TITLE
英語のサポート

### ISSUE THREAD

**Issue by tasuren** [RT-Team/rt-frontend#7]

**Comment by tuna2134** [comment]
Oh
やりたいけどRT-TEAM.github.ioがおわったらやる

**Comment by tasuren** [comment]
これの英語のサポートはちょっとめんどくさいんよね。
JavaScriptを使うかとかmiko使うのもいいかもしれない。

`rl`っていう関数をmikoに登録して、その`rl`に渡した辞書からHTMLを作るという感じにするとか。
```html
<h1>^^ rl({"ja": "タイトル", "en": "Title"}) ^^</h1>
```
がこうなる
```html
<h1><div class="lang-ja">タイトル</div><div class="lang-en" hidden>Title</div></h1>
```
`lang-<言語コード>`のクラスの`div`で囲む。  
日本語以外の言語には`hidden`を付ける。  
これをJavaScriptで`hidden`の切り替えをする。  
(一応これもmikoで実装が可能ではある。)

**Comment by tasuren** [comment]
とりあえず一般のhtmlでは以下のようにすることで配置できるようにした。
```html
<h1>^^ _(ja="タイトル", en="Title"}) ^^</h1>
```
がこうなる
```html
<h1><div class="language ja" hidden>タイトル</div><div class="language en" hidden>Title</div></h1>
```
`language`ブランチにて進行中  
`_`関数は`rt-backend`の`language`ブランチのバックエンドにて使用可能。
(JavaScriptでdivからあった言語のみhiddenを外すのは開発中...)

**Comment by tuna2134** [comment]
fmm

**Comment by tasuren** [comment]
しっかり動くようになった。
あとは翻訳だけ。

**Comment by tasuren** [comment]
実装した。
